name: Docs

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install .
      - name: Build docs
        run: |
          mkdocs build
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: site
        
        
        
